CREATE TABLE IF NOT EXISTS compliance_transactions (
    id SERIAL PRIMARY KEY,
    event_timestamp TIMESTAMPTZ NOT NULL,
    payment_type TEXT NOT NULL,
    product_category TEXT NOT NULL,
    order_price DOUBLE PRECISION NOT NULL,
    customer_job TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    billing_city TEXT NOT NULL,
    billing_state TEXT NOT NULL,
    billing_country TEXT NOT NULL,
    billing_zip TEXT NOT NULL,
    billing_latitude DOUBLE PRECISION NOT NULL,
    billing_longitude DOUBLE PRECISION NOT NULL,
    ip_address TEXT NOT NULL,
    user_agent TEXT NOT NULL,
    merchant TEXT NOT NULL,
    is_fraud BOOLEAN NOT NULL DEFAULT FALSE,
    fraud_scenario TEXT,
    assigned_label TEXT,
    similarity_score DOUBLE PRECISION,
    idempotency_key TEXT UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
